### ISSUE TITLE
Releases are not dated on the site

### ISSUE THREAD

**Issue by ericmand** [apache/beam-site#312]
I think it should be easier to see on the site the dates when Beam versions were released. There are no dates in the downloads list:
https://beam.apache.org/get-started/downloads/
Nor in any release notes:
https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12319527&version=12340528

**Comment by aaltay** [comment]
cc: @reuvenlax @melap

**Comment by iemejia** [comment]
If you need the old dates for reference I have kept them in the wikipedia article:
https://en.wikipedia.org/wiki/Apache_Beam

**Comment by melap** [comment]
I'll open a PR today for this -- thanks for the pointer to the dates Ismaël!

**Comment by melap** [comment]
This is now up on the website. I'm not sure why github didn't mark this issue resolved.
