### ISSUE TITLE
Gearpump logo is not shown on homepage

### ISSUE THREAD

**Issue by manuzhang** [apache/beam-site#321]
![snip20170916_8](https://user-images.githubusercontent.com/1191767/30510805-b3bf7c0c-9afd-11e7-9f78-c4bfd2be7e54.png)

**Comment by manuzhang** [comment]
@melap

**Comment by melap** [comment]
thanks for pointing that out. I took a look and it looks like the png didn't make it to the autogenerated content/images directory, so I am suspecting a mergebot issue. @jasonkuster to take a look from the mergebot side.

**Comment by melap** [comment]
forgot to add relevant PR that added the image: #298

**Comment by melap** [comment]
I'm wondering if it has to do with any path that has "images" in it, because I just noticed that the docker-images page #297 doesn't look like it made it to content either and is a 404 in the top nav.

**Comment by melap** [comment]
Hi @manuzhang - as a workaround in the meantime, I manually added the missing generated files so the Gearpump logo shows up now.

**Comment by manuzhang** [comment]
Thanks.
